- hosts: vaultwarden
  remote_user: root
  tasks:

  - name: Create user vaultwarden
    ansible.builtin.user:
      name: vaultwarden
      password: $6$rKRPJwebeYGVL1tm$iDBNbMkfGaTJ1odReOEA.lD7jVndeBN2AQNo9AHxCRcx6HFKQg8MQT.P3bmfEbrnhdDBDlB1WRpH/sTyjSgrX/


  - name: Download vaultwarden-server
    get_url:
      url: https://github.com/dionysius/vaultwarden-deb/releases/download/debian%2F1.32.6-0/vaultwarden_1.32.6-0.bookworm_amd64.deb
      dest: /tmp/
      mode: '0775'
      force: 'yes'

  - name: Download vaultwarden-vault
    get_url:
      url: https://github.com/dionysius/vaultwarden-web-vault-deb/releases/download/debian%2F2024.6.2-0/vaultwarden-web-vault_2024.6.2-0.bookworm_all.deb
      dest: /tmp/
      mode: '0775'
      force: 'yes'

  - name: Install dependencies
    ansible.builtin.apt:
      name: mariadb-server
      name: libpq5
      state: latest

  - name: Install web-vault
    ansible.builtin.shell:
      cmd: dpkg -i /tmp/vaultwarden-web-vault_2024.6.2-0.bookworm_all.deb

  - name: install server
    ansible.builtin.shell:
      cmd: dpkg -i /tmp/vaultwarden_1.32.6-0.bookworm_amd64.deb

