- hosts: www
  remote_user: root
  tasks:

  - name: Replicate /var/www/html/ to all webservers
    ansible.builtin.shell:
      cmd: scp /var/www/html/* https://www1.grinminer.net:/var/www/html/
      cmd: scp /var/www/html/* https://www2.grinminer.net:/var/www/html/
      cmd: scp /var/www/html/* https://www3.grinminer.net:/var/www/html/
      cmd: scp /var/www/html/* https://www4.grinminer.net:/var/www/html/
      cmd: scp /var/www/html/* https://www5.grinminer.net:/var/www/html/