[package]
name = "grinminer-form"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { git = "https://github.com/rwf2/Rocket" } 

[dependencies.rocket_dyn_templates]
version = "0.1.0"
features = ["handlebars", "tera", "minijinja"]
